server:
  port: 8080

info:
  author:
    username: xiahaihu
    email: xiahaihu2009@gmail.com


spring:
  devtools:
    livereload:
      enabled: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  main:
    banner-mode: "console"
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/publish?useUnicode=true&characterEncoding=utf-8
    username: root
    password: shearf
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    name: default

    # druid setting
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

logging:
  file: application.log
  level: info
  path: /Users/xiahaihu/logs/springboot-demo

security:
#  basic:
#    authorize-mode: authenticated
#    enabled: false
  user:
    name: shearf
    password: shearf
endpoints:
  beans:
    sensitive: false
    enabled: true
  info:
    path: /sys/info
management:
  context-path: /system
#mybatis:
#  mapper-locations: classpath:mappers/*.xml
#  type-aliases-package: com.shearf.demo.springboot.domain.entity

---
spring:
  profiles: dev

http:
  url: http://dev.localhost
  address:
    host: 127.0.0.1
    port: 8020
---
spring:
  profiles: test

http:
  url: http://dev.localhost
  address:
    host: 127.0.0.2
    port: 8021



