server:
  port: 8080

info:
  author:
    username: xiahaihu
    email: xiahaihu2009@gmail.com
endpoints:
  actuator:
    sensitive: false
    enabled: true

spring:
  devtools:
    livereload:
      enabled: true

  main:
    banner-mode: "console"
  profiles:
    active: dev
  config:
    name: "custom"


logging:
#  file: application.log
  level: warn
  path: /data/logs/springboot-demo


---
spring:
  profiles: dev

http:
  url: http://dev.localhost
  address:
    host: 127.0.0.1
    port: 8020
---
spring:
  profiles: test

http:
  url: http://dev.localhost
  address:
    host: 127.0.0.2
    port: 8021



